[build]
  command = "npm install && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20.11.0"
  NPM_VERSION = "10.2.4"
  NODE_ENV = "development"
  NETLIFY_USE_YARN = "false"

[[plugins]]
  package = "@netlify/plugin-lighthouse"
  [plugins.inputs]
    output_path = "reports/lighthouse.html"
    audits = ["/"]

[[redirects]]
  from = "http://aayushhospitalmpl.com/*"
  to = "https://www.aayushhospitalmpl.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://aayushhospitalmpl.com/*"
  to = "https://www.aayushhospitalmpl.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.aayushhospitalmpl.com/*"
  to = "https://www.aayushhospitalmpl.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-XSS-Protection = "1; mode=block"
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()"
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://gatgyhxtgqmzwjatbmzk.supabase.co;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      img-src 'self' data: https: blob:;
      font-src 'self' data: https://fonts.gstatic.com;
      connect-src 'self' https://gatgyhxtgqmzwjatbmzk.supabase.co;
      media-src 'self' https://gatgyhxtgqmzwjatbmzk.supabase.co https://voaxktqgbljtsattacbn.supabase.co;
      frame-src 'self' https://www.google.com;
      worker-src 'self' blob:;
      """

# Cache-Control optimizations
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/page-data/*"
  [headers.values]
    Cache-Control = "public, max-age=600"

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 5173
  port = 8888
  publish = "dist"
  autoLaunch = true